import { sb } from '../supabase';

// Invoice data layer for a direct order. The invoice is generated BY Maabar on
// behalf of the supplier: the supplier fills the line items + trade details, the
// server (save_order_invoice) computes the goods subtotal, the visible 5% Maabar
// fee and the total; issue_order_invoice locks it and reveals it to the buyer.

export async function fetchOrderInvoice(requestId) {
  const { data } = await sb.from('order_invoices').select('*').eq('request_id', requestId).maybeSingle();
  return data || null;
}

export async function saveOrderInvoice(requestId, { lineItems, incoterms, port, hsCode, notes, currency }) {
  const { data, error } = await sb.rpc('save_order_invoice', {
    p_request_id: requestId,
    p_line_items: lineItems,
    p_incoterms: incoterms || null,
    p_port: port || null,
    p_hs_code: hsCode || null,
    p_notes: notes || null,
    p_currency: currency || 'SAR',
  });
  if (error) throw error;
  return data;
}

export async function issueOrderInvoice(requestId) {
  const { data, error } = await sb.rpc('issue_order_invoice', { p_request_id: requestId });
  if (error) throw error;
  return data;
}

// A sensible default first line item from the order/product.
export function defaultLineItem(order) {
  const qty = Number(order?.quantity) || 1;
  const unit = Number(order?.unit_price ?? order?.price ?? 0) || 0;
  const desc = order?.product_name || order?.title_ar || order?.title_en || '';
  return [{ desc, qty, unit_price: unit, amount: qty * unit }];
}
