export const CATEGORIES = {
  ar: [
    { val: 'all', label: 'الكل' },
    { val: 'electronics', label: 'إلكترونيات' },
    { val: 'home_appliances', label: 'أجهزة منزلية' },
    { val: 'furniture', label: 'أثاث' },
    { val: 'office_furniture', label: 'أثاث مكتبي' },
    { val: 'bedroom_furniture', label: 'أثاث غرف النوم' },
    { val: 'kitchen_furniture', label: 'أثاث المطبخ' },
    { val: 'outdoor_furniture', label: 'أثاث خارجي' },
    { val: 'home_decor', label: 'ديكور منزلي' },
    { val: 'clothing', label: 'ملابس' },
    { val: 'building', label: 'مواد بناء' },
    { val: 'food', label: 'غذاء' },
    { val: 'beauty', label: 'عناية وتجميل' },
    { val: 'sports', label: 'رياضة' },
    { val: 'toys', label: 'ألعاب' },
    { val: 'auto_parts', label: 'قطع غيار' },
    { val: 'car_accessories', label: 'إكسسوارات سيارات' },
    { val: 'tires', label: 'إطارات' },
    { val: 'lubricants', label: 'زيوت ومواد تشحيم' },
    { val: 'health', label: 'صحة وطب' },
    { val: 'packaging', label: 'تعبئة وتغليف' },
    { val: 'gifts', label: 'هدايا' },
    { val: 'agriculture', label: 'زراعة' },
    { val: 'other', label: 'أخرى' },
  ],
  en: [
    { val: 'all', label: 'All' },
    { val: 'electronics', label: 'Electronics' },
    { val: 'home_appliances', label: 'Home Appliances' },
    { val: 'furniture', label: 'Furniture' },
    { val: 'office_furniture', label: 'Office Furniture' },
    { val: 'bedroom_furniture', label: 'Bedroom Furniture' },
    { val: 'kitchen_furniture', label: 'Kitchen Furniture' },
    { val: 'outdoor_furniture', label: 'Outdoor Furniture' },
    { val: 'home_decor', label: 'Home Décor' },
    { val: 'clothing', label: 'Clothing' },
    { val: 'building', label: 'Building Materials' },
    { val: 'food', label: 'Food' },
    { val: 'beauty', label: 'Beauty & Personal Care' },
    { val: 'sports', label: 'Sports' },
    { val: 'toys', label: 'Toys' },
    { val: 'auto_parts', label: 'Auto Parts' },
    { val: 'car_accessories', label: 'Car Accessories' },
    { val: 'tires', label: 'Tires' },
    { val: 'lubricants', label: 'Lubricants & Oils' },
    { val: 'health', label: 'Health & Medical' },
    { val: 'packaging', label: 'Packaging' },
    { val: 'gifts', label: 'Gifts' },
    { val: 'agriculture', label: 'Agriculture' },
    { val: 'other', label: 'Other' },
  ],
  zh: [
    { val: 'all', label: '全部' },
    { val: 'electronics', label: '电子产品' },
    { val: 'home_appliances', label: '家用电器' },
    { val: 'furniture', label: '家具' },
    { val: 'office_furniture', label: '办公家具' },
    { val: 'bedroom_furniture', label: '卧室家具' },
    { val: 'kitchen_furniture', label: '厨房家具' },
    { val: 'outdoor_furniture', label: '户外家具' },
    { val: 'home_decor', label: '家居装饰' },
    { val: 'clothing', label: '服装' },
    { val: 'building', label: '建材' },
    { val: 'food', label: '食品' },
    { val: 'beauty', label: '美容护肤' },
    { val: 'sports', label: '运动' },
    { val: 'toys', label: '玩具' },
    { val: 'auto_parts', label: '汽车配件' },
    { val: 'car_accessories', label: '汽车周边' },
    { val: 'tires', label: '轮胎' },
    { val: 'lubricants', label: '润滑油' },
    { val: 'health', label: '健康医疗' },
    { val: 'packaging', label: '包装材料' },
    { val: 'gifts', label: '礼品' },
    { val: 'agriculture', label: '农业' },
    { val: 'other', label: '其他' },
  ],
};

export const OFFER_STATUS = {
  ar: { pending: 'قيد المراجعة', accepted: 'مقبول', rejected: 'مرفوض' },
  en: { pending: 'Pending', accepted: 'Accepted', rejected: 'Rejected' },
  zh: { pending: '待审核', accepted: '已接受', rejected: '已拒绝' },
};

export const T = {
  ar: {
    tag: 'مَعبر · لوحة المورد', welcome: 'أهلاً،', desc: 'تابع عروضك ومنتجاتك ورسائلك من مكان واحد', supplierStageLabel: 'حالة الحساب', supplierIdLabel: 'معرّف مورد مَعبر',
    overview: 'نظرة عامة', myProducts: 'منتجاتي', offers: 'عروضي', addProduct: 'إضافة منتج',
    messages: 'الرسائل', settings: 'إعداداتي', offersCount: 'عروض مقدمة',
    productsCount: 'منتجات نشطة', messagesCount: 'رسائل جديدة',
    browseRequests: 'تصفح طلبات التجار', addNewProduct: 'إضافة منتج جديد',
    quickActions: 'الإجراءات السريعة', stats: 'الإحصائيات', backHome: 'العودة للرئيسية ←', back: 'رجوع ←',
    myOffers: 'عروضي', noOffers: 'ما قدمت عروض بعد', browseReqs: 'تصفح الطلبات',
    trackingPrompt: 'أدخل رقم التتبع لإخطار التاجر', trackingNum: 'رقم التتبع', send: 'إرسال',
    contactTrader: 'تواصل مع التاجر', tracking: 'رقم التتبع:',
    messagesTitle: 'الرسائل', noMessages: 'ما عندك رسائل بعد',
    addProductTitle: 'إضافة منتج جديد', myProductsTitle: 'منتجاتي', noProducts: 'ما أضفت منتجات بعد',
    nameAr: 'اسم المنتج بالعربي', nameEn: 'اسم المنتج بالإنجليزي *', nameZh: 'اسم المنتج بالصيني *',
    category: 'التصنيف *', currency: 'العملة *', price: 'السعر الابتدائي *', moq: 'MOQ *', descLabel: 'الوصف بالعربي', descEnLabel: 'الوصف بالإنجليزي *', descHint: 'العربي اختياري، والإنجليزي هو الأساس لعرض المنتج وترجمته لاحقًا.',
    save: 'حفظ', cancel: 'إلغاء', saving: '...',
    edit: 'تعديل', delete: 'حذف', confirmDelete: 'هل تبي تحذف هذا المنتج؟',
    active: 'نشط', inactive: 'موقوف', toggleActive: 'تفعيل/إيقاف',
    needsAttention: 'يحتاج انتباهك', acceptedOffer: 'عرض مقبول — تواصل مع التاجر',
    offerRejected: 'تم رفض عرضك على',
    uploadImage: 'رفع صورة', uploadVideo: 'رفع فيديو',
    uploadingImage: 'جاري رفع الصورة...', uploadingVideo: 'جاري رفع الفيديو...',
    imageUploaded: 'تم رفع الصورة', videoUploaded: 'تم رفع الفيديو', maxVideo: 'الحد الأقصى للفيديو 50MB',
    galleryImages: 'صور المنتج', addMoreImages: 'إضافة صور أخرى', galleryHint: 'حتى 8 صور — الصورة الأولى هي الرئيسية حالياً', maxImagesReached: 'وصلت للحد الأقصى (8 صور)', maxImagesError: 'يمكن رفع 8 صور كحد أقصى', removeMedia: 'حذف', previewStep: 'معاينة قبل النشر', continueToPreview: 'متابعة للمعاينة', backToEdit: 'رجوع للتعديل', publishNow: 'نشر المنتج', previewNote: 'راجع الوسائط والمواصفات والسعر قبل النشر. العملة المعروضة هنا لا تغيّر عملة المنتج الأصلية.', previewBadge: 'معاينة', previewEmptyMedia: 'ما تمت إضافة صور بعد', primaryImage: 'الصورة الرئيسية', videoLimitHint: 'فيديو واحد فقط لكل منتج',
    specsTitle: 'مواصفات المنتج', specMaterial: 'الخامة / المادة', specDimensions: 'الأبعاد / المقاس', specWeight: 'وزن القطعة', specColors: 'الألوان أو الخيارات', specPackaging: 'تفاصيل التغليف', specCustomization: 'التخصيص / OEM', specLeadTime: 'مدة التجهيز (أيام)', productSavedWithFallback: 'تم حفظ المنتج، لكن بعض الحقول الجديدة تحتاج تفعيل قاعدة البيانات حتى تُحفظ بالكامل.',
    sampleSettings: 'إعدادات العينة', sampleAvailable: 'متاح للعينة',
    samplePrice: 'سعر العينة (ريال) *', sampleShipping: 'تكلفة الشحن (ريال)',
    sampleMaxQty: 'الحد الأقصى للكمية', sampleNote: 'ملاحظة للعينة',
    settingsTitle: 'إعدادات الحساب', companyName: 'اسم الشركة',
    bioAr: 'وصف الشركة بالعربي', bioEn: 'وصف الشركة بالإنجليزي', bioZh: 'وصف الشركة بالصيني',
    whatsapp: 'واتساب', wechat: 'WeChat', city: 'المدينة', country: 'الدولة',
    tradeLink: 'رابط صفحة المتجر / الملف التجاري', speciality: 'تخصص الشركة', minOrder: 'الحد الأدنى لقيمة الطلب (ريال)',
    logo: 'لوقو / صورة الشركة', factoryImages: 'صور المصنع (حتى 3)',
    uploadLogo: 'رفع اللوقو', uploadFactory: 'إضافة صورة', uploadingLogo: 'جاري الرفع...',
    saveSettings: 'حفظ الإعدادات', settingsSaved: 'تم حفظ التغييرات', saveAndContinue: 'احفظ وانتقل للخطوة التالية', verificationReviewRequired: 'افتح خطوة المراجعة النهائية قبل إرسال طلب التحقق.', days: 'يوم',
    verificationTab: 'التحقق', verificationTitle: 'أكمل التحقق التجاري', verificationIntro: 'أرسل بيانات التحقق والمستندات من هنا بعد إنشاء الحساب. لن نطلبها في التسجيل الأولي.',
    verificationStatusIncomplete: 'التحقق غير مكتمل', verificationStatusComplete: 'تم إرسال التحقق للمراجعة', verificationStatusLocked: 'الحساب الآن تحت المراجعة',
    verificationCtaTitle: 'أكمل التحقق التجاري', verificationCtaBody: 'أرسل السجل التجاري وصورة المصنع وبيانات الخبرة حتى يدخل طلبك مرحلة المراجعة.', verificationCtaAction: 'أكمل التحقق ←',
    uploadProductsBannerTitle: 'حسابك قيد المراجعة — ابدأ برفع منتجاتك الآن', uploadProductsBannerBody: 'بعد القبول، ستظهر منتجاتك فوراً للتجار السعوديين. ارفعها الآن وكن جاهزاً من اليوم الأول.', uploadProductsBannerAction: 'ارفع منتجاتك الآن ←',
    productDraftPendingApprovalLabel: 'مسودة — تُنشر فور توثيق الحساب',
    regNumber: 'رقم تسجيل الشركة *', yearsExp: 'سنوات الخبرة *', employees: 'عدد الموظفين (اختياري)', businessLicense: 'رخصة الأعمال أو هوية المنشأة *', factoryPhoto: 'صورة المصنع أو المستودع *', replaceFile: 'استبدال الملف', viewCurrentFile: 'عرض الملف الحالي', secureStorageNote: 'يتم حفظ هذه الملفات داخل تخزين خاص، ولا تُعرض بروابط عامة.', verificationSubmitted: 'تم إرسال التحقق بنجاح. الحساب الآن تحت المراجعة.', verificationMissing: 'يرجى تعبئة جميع حقول التحقق المطلوبة ورفع المستندات.', verificationVideoRequired: 'يرجى رفع مقطع فيديو للمصنع قبل إرسال التحقق.', verificationProfileRequired: 'أكمل أولاً بيانات الشركة الأساسية واحفظها قبل إرسال التحقق.',
    payoutTab: 'المدفوعات', payoutTitle: 'إعدادات استلام الدفعات', payoutIntro: 'أضف بياناتك البنكية لتكون جاهزًا لاستقبال الدفعات مستقبلًا عبر معبر.', payoutNote: 'يتم حفظ هذه البيانات بشكل آمن.', payoutLocked: 'إعدادات الدفعات تفتح بعد الموافقة على حسابك.', payoutCtaTitle: 'أكمل بيانات الدفعات', payoutCtaBody: 'حسابك مقبول، لكن بياناتك البنكية ما زالت غير مكتملة.', payoutCtaAction: 'إكمال بيانات الدفعات ←', payoutSaved: 'تم حفظ بيانات الدفعات', payoutReassurance: 'بياناتك البنكية تُستخدم فقط لاستلام المدفوعات. مَعبر لن يخصم أي مبلغ منك.', beneficiaryName: 'اسم المستفيد', bankName: 'اسم البنك', bankAccountNumber: 'رقم الحساب البنكي', swiftCode: 'SWIFT / BIC', bankAddress: 'عنوان البنك', preferredCurrency: 'العملة المفضلة', branchNameOptional: 'اسم الفرع (اختياري)', ibanOptional: 'IBAN (اختياري)', savePayout: 'حفظ بيانات الدفعات', onboardingTitle: 'طلبك ما زال في مرحلة الانضمام', onboardingBody: 'هذه لوحة المورد الأساسية، لكن الإجراءات الأساسية ما زالت مقفلة. أكمل ملف الشركة وأرسل التحقق حتى يدخل الحساب مرحلة المراجعة.', onboardingProgress: 'تقدّم الطلب', onboardingLockedTitle: 'المزايا المقفلة حتى التوثيق', onboardingLockedBody: 'الطلبات والعروض والمنتجات والرسائل وكل الإجراءات الأساسية تفتح فقط بعد اعتماد التحقق.', onboardingStepApply: '1) أكمل الملف الأساسي', onboardingStepReview: '2) أرسل التحقق للمراجعة', onboardingStepVisibility: '3) افتح التجربة الكاملة بعد التوثيق', onboardingGoSettings: 'إعدادات الملف', onboardingStatusDraft: 'verification_required', onboardingVerificationReady: 'بعد إرسال التحقق ينتقل الحساب مباشرة إلى مرحلة المراجعة.', verificationSubmitAction: 'إرسال التحقق',
  },
  en: {
    tag: 'Maabar · Supplier Dashboard', welcome: 'Welcome,', desc: 'Manage your offers, products and messages in one place', supplierStageLabel: 'Account status', supplierIdLabel: 'Maabar Supplier ID',
    overview: 'Overview', myProducts: 'My Products', offers: 'My Offers', addProduct: 'Add Product',
    messages: 'Messages', settings: 'Settings', offersCount: 'Offers Submitted',
    productsCount: 'Active Products', messagesCount: 'New Messages',
    browseRequests: 'Browse Trader Requests', addNewProduct: 'Add New Product',
    quickActions: 'Quick Actions', stats: 'Overview', backHome: '← Back to Home', back: '← Back',
    myOffers: 'My Offers', noOffers: 'No offers yet', browseReqs: 'Browse Requests',
    trackingPrompt: 'Enter tracking number to notify buyer', trackingNum: 'Tracking number', send: 'Send',
    contactTrader: 'Contact Trader', tracking: 'Tracking:',
    messagesTitle: 'Messages', noMessages: 'No messages yet',
    addProductTitle: 'Add New Product', myProductsTitle: 'My Products', noProducts: 'No products yet',
    nameAr: 'Arabic Name', nameEn: 'English Name *', nameZh: 'Chinese Name *',
    category: 'Category *', currency: 'Currency *', price: 'Starting Price *', moq: 'MOQ *', descLabel: 'Arabic Description', descEnLabel: 'English Description *', descHint: 'Arabic is optional. English is the main source for listing quality and later translation.',
    save: 'Save', cancel: 'Cancel', saving: '...',
    edit: 'Edit', delete: 'Delete', confirmDelete: 'Delete this product?',
    active: 'Active', inactive: 'Paused', toggleActive: 'Toggle',
    needsAttention: 'Needs Attention', acceptedOffer: 'Offer accepted — Contact trader',
    offerRejected: 'Your offer was rejected on',
    uploadImage: 'Upload Image', uploadVideo: 'Upload Video',
    uploadingImage: 'Uploading...', uploadingVideo: 'Uploading...',
    imageUploaded: 'Image uploaded', videoUploaded: 'Video uploaded', maxVideo: 'Max 50MB',
    galleryImages: 'Product Images', addMoreImages: 'Add More Images', galleryHint: 'Up to 8 images — the first image stays the primary cover', maxImagesReached: 'Maximum reached (8 images)', maxImagesError: 'You can upload up to 8 images', removeMedia: 'Remove', previewStep: 'Preview Before Publish', continueToPreview: 'Continue to Preview', backToEdit: 'Back to Edit', publishNow: 'Publish Product', previewNote: 'Review media, specs, and pricing before publishing. Display currency never replaces the saved source product currency.', previewBadge: 'Preview', previewEmptyMedia: 'No product images yet', primaryImage: 'Primary image', videoLimitHint: 'One product video only',
    specsTitle: 'Product Specifications', specMaterial: 'Material', specDimensions: 'Dimensions / Size', specWeight: 'Unit Weight', specColors: 'Colors / Variants', specPackaging: 'Packaging Details', specCustomization: 'Customization / OEM', specLeadTime: 'Lead Time (days)', productSavedWithFallback: 'Product saved, but some new fields still need the DB migration before they can persist fully.',
    sampleSettings: 'Sample Settings', sampleAvailable: 'Available for Sample',
    samplePrice: 'Sample Price (SAR) *', sampleShipping: 'Shipping Cost (SAR)',
    sampleMaxQty: 'Max Sample Qty', sampleNote: 'Sample Note',
    settingsTitle: 'Account Settings', companyName: 'Company Name',
    bioAr: 'Description (Arabic)', bioEn: 'Description (English)', bioZh: 'Description (Chinese)',
    whatsapp: 'WhatsApp', wechat: 'WeChat', city: 'City', country: 'Country',
    tradeLink: 'Trade profile / storefront link', speciality: 'Specialty', minOrder: 'Minimum order value (SAR)',
    logo: 'Company Logo', factoryImages: 'Factory Images (up to 3)',
    uploadLogo: 'Upload Logo', uploadFactory: 'Add Image', uploadingLogo: 'Uploading...',
    saveSettings: 'Save Settings', settingsSaved: 'Changes saved', saveAndContinue: 'Save and move to step 2', verificationReviewRequired: 'Open the final review step before submitting verification.', days: 'days',
    verificationTab: 'Verification', verificationTitle: 'Complete business verification', verificationIntro: 'Submit the full verification details and documents here after signup. They are no longer required during initial registration.',
    verificationStatusIncomplete: 'Verification incomplete', verificationStatusComplete: 'Verification submitted for review', verificationStatusLocked: 'Account is currently under review',
    verificationCtaTitle: 'Complete your business verification', verificationCtaBody: 'Submit your registration, factory evidence, and experience details so your application can enter review.', verificationCtaAction: 'Complete verification →',
    uploadProductsBannerTitle: 'Account under review — Start uploading your products now', uploadProductsBannerBody: 'Once approved, your products will be immediately visible to Saudi buyers. Upload now and be ready from day one.', uploadProductsBannerAction: 'Upload Products Now →',
    productDraftPendingApprovalLabel: 'Draft — will go live when account is verified',
    regNumber: 'Company Registration Number *', yearsExp: 'Years of Experience *', employees: 'Number of Employees (optional)', businessLicense: 'Business License or Company ID *', factoryPhoto: 'Factory or Warehouse Photo *', replaceFile: 'Replace file', viewCurrentFile: 'View current file', secureStorageNote: 'These files are stored in private storage and are never exposed through public URLs.', verificationSubmitted: 'Verification submitted successfully. Your account is now under review.', verificationMissing: 'Please complete all required verification fields and upload the required documents.', verificationVideoRequired: 'Please upload at least one factory video before submitting verification.', verificationProfileRequired: 'Complete and save the basic company profile before submitting verification.',
    payoutTab: 'Payout', payoutTitle: 'Payout settings', payoutIntro: 'Add your bank details so you are ready to receive future payouts through Maabar.', payoutNote: 'This information is stored securely.', payoutLocked: 'Payout details unlock after your account is approved.', payoutCtaTitle: 'Complete your payout details', payoutCtaBody: 'Your account is approved, but your bank payout details are still incomplete.', payoutCtaAction: 'Add payout details →', payoutSaved: 'Payout details saved', payoutReassurance: 'Your bank details are only used to receive payments. Maabar will never charge you.', beneficiaryName: 'Beneficiary Name', bankName: 'Bank Name', bankAccountNumber: 'Bank Account Number', swiftCode: 'SWIFT / BIC', bankAddress: 'Bank Address', preferredCurrency: 'Preferred Currency', branchNameOptional: 'Branch Name (optional)', ibanOptional: 'IBAN (optional)', savePayout: 'Save payout details', onboardingTitle: 'Your account is still in the supplier application stage', onboardingBody: 'This is the supplier dashboard, but core actions are still locked. Complete your company profile and submit verification so the account can enter review.', onboardingProgress: 'Application progress', onboardingLockedTitle: 'Locked until verification is approved', onboardingLockedBody: 'Products, offers, messages, trader requests, and every core supplier action unlock only after verification is approved.', onboardingStepApply: '1) Complete the basic profile', onboardingStepReview: '2) Submit verification for review', onboardingStepVisibility: '3) Unlock the full supplier experience after verification', onboardingGoSettings: 'Profile settings', onboardingStatusDraft: 'verification_required', onboardingVerificationReady: 'Once you submit verification, the account moves directly into review.', verificationSubmitAction: 'Submit verification',
  },
  zh: {
    tag: 'Maabar · 供应商控制台', welcome: '欢迎，', desc: '在一个地方管理您的报价、产品和消息', supplierStageLabel: '账户状态', supplierIdLabel: 'Maabar 供应商编号',
    overview: '概览', myProducts: '我的产品', offers: '我的报价', addProduct: '添加产品',
    messages: '消息', settings: '账户设置', offersCount: '已提交报价',
    productsCount: '活跃产品', messagesCount: '新消息',
    browseRequests: '浏览采购商需求', addNewProduct: '添加新产品',
    quickActions: '快速操作', stats: '数据概览', backHome: '← 返回首页', back: '← 返回',
    myOffers: '我的报价', noOffers: '暂无报价', browseReqs: '浏览需求',
    trackingPrompt: '输入物流单号以通知采购商', trackingNum: '物流单号', send: '发送',
    contactTrader: '联系采购商', tracking: '物流单号：',
    messagesTitle: '消息', noMessages: '暂无消息',
    addProductTitle: '添加新产品', myProductsTitle: '我的产品', noProducts: '暂无产品',
    nameAr: '阿拉伯语名称', nameEn: '英文名称 *', nameZh: '中文名称 *',
    category: '产品分类 *', currency: '货币 *', price: '起始价格 *', moq: '最小起订量 *', descLabel: '阿拉伯语描述', descEnLabel: '英文描述 *', descHint: '阿拉伯语可选，英文作为主描述，后续更方便做展示与翻译。',
    save: '保存', cancel: '取消', saving: '...',
    edit: '编辑', delete: '删除', confirmDelete: '确认删除此产品？',
    active: '上架', inactive: '下架', toggleActive: '切换状态',
    needsAttention: '需要处理', acceptedOffer: '报价已接受 — 联系采购商',
    offerRejected: '您的报价被拒绝',
    uploadImage: '上传图片', uploadVideo: '上传视频',
    uploadingImage: '上传中...', uploadingVideo: '上传中...',
    imageUploaded: '图片已上传', videoUploaded: '视频已上传', maxVideo: '最大 50MB',
    galleryImages: '产品图片', addMoreImages: '继续添加图片', galleryHint: '最多 8 张图片 — 第一张将作为主图', maxImagesReached: '已达到上限（8 张）', maxImagesError: '最多可上传 8 张图片', removeMedia: '删除', previewStep: '发布前预览', continueToPreview: '继续预览', backToEdit: '返回编辑', publishNow: '发布产品', previewNote: '发布前请先确认媒体、规格和价格。这里的显示货币不会替代产品原始货币。', previewBadge: '预览', previewEmptyMedia: '暂未添加产品图片', primaryImage: '主图', videoLimitHint: '每个产品仅支持 1 个视频',
    specsTitle: '产品规格', specMaterial: '材质', specDimensions: '尺寸 / 规格', specWeight: '单件重量', specColors: '颜色 / 款式', specPackaging: '包装信息', specCustomization: '定制 / OEM', specLeadTime: '交期（天）', productSavedWithFallback: '产品已保存，但部分新字段仍需要先执行数据库迁移后才能完整持久化。',
    sampleSettings: '样品设置', sampleAvailable: '可提供样品',
    samplePrice: '样品价格 (USD) *', sampleShipping: '运费 (USD)',
    sampleMaxQty: '最大样品数量', sampleNote: '样品备注',
    settingsTitle: '账户设置', companyName: '公司名称',
    bioAr: '公司介绍（阿拉伯语）', bioEn: '公司介绍（英语）', bioZh: '公司介绍（中文）',
    whatsapp: 'WhatsApp', wechat: 'WeChat', city: '城市', country: '国家',
    tradeLink: '贸易主页 / 店铺链接', speciality: '专业领域', minOrder: '最低订单金额 (USD)',
    logo: '公司Logo', factoryImages: '工厂图片（最多3张）',
    uploadLogo: '上传Logo', uploadFactory: '添加图片', uploadingLogo: '上传中...',
    saveSettings: '保存设置', settingsSaved: '保存成功', saveAndContinue: '保存并进入第 2 步', verificationReviewRequired: '提交认证前，请先打开最终确认步骤。', days: '天',
    verificationTab: '认证', verificationTitle: '完成企业认证', verificationIntro: '注册后在这里补充完整认证资料和文件，初始注册不再要求一次填完。',
    verificationStatusIncomplete: '认证未完成', verificationStatusComplete: '认证资料已提交审核', verificationStatusLocked: '账户正在审核中',
    verificationCtaTitle: '请完成企业认证', verificationCtaBody: '请提交注册资料、工厂证明和经验信息，审核流程才会开始。', verificationCtaAction: '去完成认证 →',
    uploadProductsBannerTitle: '账户审核中 — 现在开始上传您的产品', uploadProductsBannerBody: '审核通过后，您的产品将立即对沙特买家可见。提前上传，从第一天起就做好准备。', uploadProductsBannerAction: '立即上传产品 →',
    productDraftPendingApprovalLabel: '草稿 — 账户审核通过后自动上线',
    regNumber: '公司注册号 *', yearsExp: '从业年限 *', employees: '员工人数（可选）', businessLicense: '营业执照或企业身份证明 *', factoryPhoto: '工厂或仓库照片 *', replaceFile: '更换文件', viewCurrentFile: '查看当前文件', secureStorageNote: '这些文件保存在私有存储中，不会通过公开链接暴露。', verificationSubmitted: '认证资料已提交，账户当前处于审核中。', verificationMissing: '请填写所有必填认证信息并上传所需文件。', verificationVideoRequired: '请在提交认证前至少上传一个工厂视频。', verificationProfileRequired: '请先完成并保存基础公司资料，再提交认证。',
    payoutTab: '收款', payoutTitle: '收款设置', payoutIntro: '请补充您的银行信息，以便未来通过 Maabar 接收款项。', payoutNote: '这些信息会被安全保存。', payoutLocked: '账户审核通过后才可填写收款资料。', payoutCtaTitle: '请完成收款资料', payoutCtaBody: '您的账户已通过审核，但银行收款资料仍未填写完整。', payoutCtaAction: '去填写收款资料 →', payoutSaved: '收款信息已保存', payoutReassurance: '您的银行信息仅用于收款，Maabar 不会向您收取任何费用。', beneficiaryName: '收款人姓名', bankName: '银行名称', bankAccountNumber: '银行账号', swiftCode: 'SWIFT / BIC', bankAddress: '银行地址', preferredCurrency: '首选货币', branchNameOptional: '分行名称（可选）', ibanOptional: 'IBAN（可选）', savePayout: '保存收款信息', onboardingTitle: '您的账户仍处于供应商申请阶段', onboardingBody: '这里已经是供应商控制台，但核心操作仍然锁定。请先完善公司资料并提交认证，让账户进入审核阶段。', onboardingProgress: '申请进度', onboardingLockedTitle: '认证通过前保持锁定', onboardingLockedBody: '产品、报价、消息、采购需求以及所有核心供应商操作，都要在认证通过后才会开放。', onboardingStepApply: '1) 完成基础资料', onboardingStepReview: '2) 提交认证进入审核', onboardingStepVisibility: '3) 认证通过后解锁完整供应商体验', onboardingGoSettings: '资料设置', onboardingStatusDraft: 'verification_required', onboardingVerificationReady: '提交认证后，账户会直接进入审核阶段。', verificationSubmitAction: '提交认证',
  },
};
