// Single source of truth for Maabar's Terms & Conditions.
//
// Two surfaces consume this:
//   1. The dedicated /terms page rendered by src/pages/Terms.jsx
//   2. The supplier signup modal opened from src/pages/Login.jsx
//
// Previously each surface kept its own copy — Login.jsx had a short
// 8-section variant and Terms.jsx had this full 18-section variant —
// which created a compliance risk: a supplier agreeing to the modal
// version was not seeing the same content as the linked /terms page.
// Both surfaces now import the same SECTIONS object below.
//
// All three languages stay perfectly parallel: same 18 sections, same
// numbering, same headings. Section bodies use \n for line breaks; the
// renderers apply whiteSpace: pre-line so they render as visible breaks.

export const SECTIONS = {
  ar: [
    { title: '1. تعريف المنصة', body: 'مَعبر منصة وساطة تجارية إلكترونية تربط التجار السعوديين بالموردين الصينيين. تعمل مَعبر بوصفها وسيطاً تجارياً محايداً فقط، وليست طرفاً في أي صفقة تُبرم بين المستخدمين.\nمسؤولية التحقق من المنتجات وجودتها وشروط التسليم تقع على عاتق الطرفين المتعاقدَين. تلتزم مَعبر بإدارة آلية الدفع والنزاعات وفق ما هو منصوص عليه في هذه الشروط.' },
    { title: '2. شروط التسجيل', body: 'للتاجر:\n▪ يجب أن يكون مقيماً أو يمارس نشاطاً تجارياً في المملكة العربية السعودية.\n▪ يُقر بصحة بياناته المقدمة عند التسجيل.\nللمورد:\n▪ يجب أن يكون لديه سجل تجاري ساري.\n▪ يخضع لمراجعة وموافقة مَعبر قبل تفعيل حسابه، وقد يستغرق الاعتماد 3-5 أيام عمل.\nيحق لمَعبر تعليق أي حساب أو إلغاؤه في حال ثبت انتهاك هذه الشروط.' },
    { title: '3. آلية إبرام العقود', body: 'تُبرم الصفقات عبر آلية العرض والقبول:\n▪ يرفع التاجر طلباً تفصيلياً بالمنتج المطلوب.\n▪ يُقدّم الموردون عروضهم وفق مواصفات الطلب.\n▪ يختار التاجر العرض الأنسب ويؤكده.\nيُعدّ العقد ملزماً للطرفين فور تحويل التاجر للدفعة الأولى. قبل التحويل، يحق لكلا الطرفين إلغاء الطلب أو سحب العرض دون أي التزام مالي. تحتفظ مَعبر بسجل رقمي لكل عقد مبرم لمدة 3 سنوات.' },
    { title: '4. نظام الدفع المرحلي', body: 'تتيح مَعبر ثلاثة خيارات للدفع، يختار التاجر أحدها عند تأكيد الصفقة:\n\n4.1 نظام 30٪ / 70٪\n▪ يدفع التاجر 30٪ من قيمة الصفقة لتمكين المورد من بدء التجهيز.\n▪ تُحجز الدفعة الأولى (30٪) وتُحوَّل للمورد فور تأكيد بدء التجهيز.\n▪ يدفع التاجر الباقي (70٪) بعد تلقّي إشعار «الشحنة جاهزة» من المورد.\n▪ تحتفظ مَعبر بالدفعة الثانية (70٪) حتى تأكيد استلام التاجر للبضاعة.\n\n4.2 نظام 50٪ / 50٪\n▪ يدفع التاجر 50٪ مقدماً مع أولوية في جدول التجهيز.\n▪ يدفع التاجر الباقي (50٪) بعد إشعار «الشحنة جاهزة».\n▪ تحتفظ مَعبر بالدفعة الثانية (50٪) حتى تأكيد الاستلام.\n\n4.3 نظام 100٪\n▪ دفعة كاملة واحدة تُعجّل عملية الشحن.\n▪ يشحن المورد فور استلام التأكيد من مَعبر.\n\nملاحظة مهمة:\nالدفعة الأولى في أنظمة 30/70 و50/50 تمثّل التزام التاجر وتُمكّن المورد من بدء الإنتاج. لا تُفرج مَعبر عن الدفعة الثانية للمورد إلا بعد تأكيد استلام التاجر للبضاعة أو انقضاء مدة الاعتراض المقررة.' },
    { title: '5. سياسة مدة التسليم', body: 'تُحدَّد مدة التسليم المتوقعة في كل صفقة بشكل منفصل بالاتفاق بين التاجر والمورد، وتُدرج في تفاصيل العرض قبل تأكيد الصفقة.\nيلتزم المورد بإشعار التاجر فور جاهزية الشحنة، وبأي تأخير متوقع قبل موعد الشحن المتفق عليه. تُعدّ المدة المُدرجة في العرض المعتمد جزءاً لا يتجزأ من الاتفاق الملزم بين الطرفين.' },
    { title: '6. رسوم المنصة والعمولة', body: 'تعمل مَعبر حالياً برسوم 4٪ على الصفقات المُبرمة عبر المنصة.\nتحتفظ مَعبر بحق تعديل هيكل الرسوم مستقبلاً، مع إشعار المستخدمين المسجّلين قبل 30 يوماً من تاريخ تطبيق أي تغيير.' },
    { title: '7. البضائع المسموح بها والمحظورة', body: 'تقتصر المنصة على الصفقات المتعلقة بالبضائع المرخصة وفق أنظمة التجارة السعودية. يُحظر تداول أي مما يلي عبر مَعبر:\n▪ المنتجات المقلدة أو المنتهكة لحقوق الملكية الفكرية.\n▪ البضائع التي تستوجب شهادة مطابقة سعودية (SASO) دون الحصول عليها.\n▪ المنتجات الغذائية والدوائية دون موافقة هيئة الغذاء والدواء السعودية.\n▪ الأسلحة وذخائرها وملحقاتها بكل أنواعها.\n▪ المواد المخدرة والمؤثرات العقلية.\n▪ أي بضائع محظور استيرادها أو تداولها بموجب الأنظمة السعودية أو الاتفاقيات الدولية المعمول بها في المملكة.\nيتحمل التاجر والمورد كامل المسؤولية القانونية عن أي مخالفة لهذا البند.' },
    { title: '8. حقوق وواجبات التاجر', body: 'الحقوق:\n▪ الاطلاع على عروض الموردين المعتمدين كاملةً.\n▪ المطالبة بالاسترداد في حالات التقصير الثابتة وفق المادة 10.\n▪ تقييم الموردين بعد اكتمال الصفقة.\n▪ التواصل مع فريق دعم مَعبر في أي وقت.\nالواجبات:\n▪ تقديم معلومات دقيقة وكاملة في طلبات الشراء.\n▪ الالتزام بالدفع بعد قبول العرض وفق النظام المختار.\n▪ الإبلاغ عن أي مشكلة خلال 7 أيام من تاريخ الاستلام الفعلي.\n▪ إجراء جميع المدفوعات عبر منصة مَعبر حصراً.' },
    { title: '9. حقوق وواجبات المورد', body: 'الحقوق:\n▪ استلام المدفوعات وفق الجدول المتفق عليه في الصفقة.\n▪ الرد على الشكاوى وتقديم توثيق كافٍ للدفاع عن موقفه.\nالواجبات:\n▪ الالتزام بمواصفات المنتج المتفق عليها في العرض المعتمد.\n▪ التسليم في المدة المحددة في الصفقة.\n▪ إشعار التاجر فوراً بأي تأخير متوقع مع بيان الأسباب.\n▪ عدم طلب أي مدفوعات خارج منصة مَعبر تحت أي مسمى.' },
    { title: '10. سياسة الاسترداد والمشاكل', body: '10.1 بضاعة تالفة أو مخالفة للوصف:\n▪ للتاجر 7 أيام من تاريخ الاستلام الفعلي لرفع شكوى موثقة بصور أو فيديو.\n▪ تراجع مَعبر الشكوى خلال 3 أيام عمل وتُصدر قرارها.\n▪ في حال ثبوت التقصير: تُرجع مَعبر الدفعة المحجوزة للتاجر وتوقف حساب المورد مؤقتاً.\n\n10.2 عدم الشحن بعد استلام الدفعة الثانية:\n▪ يحق للتاجر رفع شكوى فورية.\n▪ تتدخل مَعبر وتوقف حساب المورد مؤقتاً وتُرجع الدفعة الثانية المحجوزة للتاجر كاملة.\n\n10.3 الدفعة الأولى في نظام 30٪/70٪:\nتُحوَّل الـ30٪ للمورد فور تأكيد بدء التجهيز، لأنها تمثّل تكلفة المواد الخام والإنتاج الفعلي. في حال ثبوت تقصير المورد قبل بدء التجهيز الفعلي، تسترد مَعبر هذا المبلغ وتُعيده للتاجر كاملاً.\n\n10.4 الدفعة الأولى في نظام 50٪/50٪:\nتبقى الـ50٪ محجوزةً لدى مَعبر ولا تُحوَّل للمورد إلا بعد تأكيد جاهزية الشحنة. في حال ثبوت تقصير المورد، تُرجع مَعبر هذا المبلغ للتاجر كاملاً.\n\n10.5 قرار مَعبر في النزاعات نهائي وملزم للطرفين.' },
    { title: '11. تسوية النزاعات', body: 'تلتزم مَعبر بالبت في النزاعات خلال 7 أيام عمل من استلام الشكوى المكتملة بأدلتها. تعمل مَعبر كطرف محايد وتستند إلى الأدلة المقدمة من الطرفين حصراً.\nقرار مَعبر نهائي وملزم داخل المنصة. في حال رغبة أي طرف في التقاضي الخارجي، يختص القضاء السعودي بالنظر في النزاع وفق أنظمة المملكة.' },
    { title: '12. التواصل والدعم', body: 'يمكن التواصل مع فريق مَعبر عبر القنوات التالية:\n▪ البريد الإلكتروني: support@maabar.io\nللشكاوى الرسمية: يُرسل بريد إلكتروني مفصّل إلى support@maabar.io مع رقم الصفقة والأدلة المرفقة.' },
    { title: '13. الخصوصية وحماية البيانات', body: 'تلتزم مَعبر بنظام حماية البيانات الشخصية السعودي (PDPL). نجمع البيانات الضرورية فقط لتشغيل المنصة — كالاسم والبريد الإلكتروني وبيانات الصفقات — ولا نبيعها أو نشاركها مع أي طرف ثالث إلا بموجب أمر قضائي أو متطلب نظامي.\nيحق لكل مستخدم في أي وقت:\n▪ طلب الاطلاع على بياناته الشخصية المحفوظة لدينا.\n▪ طلب تصحيح أي بيانات غير دقيقة.\n▪ طلب حذف بياناته بعد انتهاء العلاقة التعاقدية، مع الاحتفاظ بما يلزم قانونياً لمدة 3 سنوات.\nللتواصل بشأن الخصوصية: support@maabar.io' },
    { title: '14. الأمن التقني', body: 'تعتمد مَعبر الإجراءات التقنية التالية لحماية بيانات المستخدمين:\n▪ شهادة SSL سارية لتشفير جميع البيانات المتبادلة بين المستخدم والمنصة.\n▪ سياسات تحكم صارمة على قاعدة البيانات (Row Level Security) تضمن أن كل مستخدم لا يصل إلا لبياناته الخاصة.\n▪ بيانات الدفع والبطاقات البنكية لا تمر عبر خوادم مَعبر ولا تُخزَّن لديها — تُعالَج مباشرةً عبر بوابة ميسر المرخصة من البنك المركزي السعودي (ساما).\nفي حال وقوع اختراق أمني يمس بيانات المستخدمين، تلتزم مَعبر بإشعار المتضررين خلال 72 ساعة من اكتشاف الاختراق وفق متطلبات الهيئة الوطنية للأمن السيبراني.' },
    { title: '15. البضائع المحظورة — إقرار المستخدم', body: 'بقبول هذه الشروط، يُقر كل من التاجر والمورد بأنه لن يستخدم مَعبر في تداول أي بضائع محظورة وفق المادة 7. تحتفظ مَعبر بحق إلغاء أي صفقة وتجميد الحساب فور اكتشاف أي مخالفة، دون إعادة أي مدفوعات مرتبطة بالصفقة المخالفة.' },
    { title: '16. تعديل الشروط', body: 'تحتفظ مَعبر بحق تعديل هذه الشروط في أي وقت. يُشترط إشعار المستخدمين المسجّلين بأي تعديل جوهري قبل 30 يوماً على الأقل من تاريخ سريانه عبر البريد الإلكتروني المسجّل.\nاستمرار استخدام المنصة بعد التعديل يُعدّ قبولاً ضمنياً لجميع التعديلات.' },
    { title: '17. حفظ السجلات', body: 'تحتفظ مَعبر بسجلات العقود والمحادثات والمدفوعات لمدة 3 سنوات من تاريخ إتمام الصفقة أو إنهائها.' },
    { title: '18. الاختصاص القضائي', body: 'تخضع هذه الشروط لأنظمة المملكة العربية السعودية. في حال نشوء نزاع لم يُسوَّ وفق آلية مَعبر الداخلية، يختص القضاء السعودي بالنظر فيه.' },
  ],
  en: [
    { title: '1. Platform Definition', body: 'Maabar is an electronic trade intermediary platform connecting Saudi traders with Chinese suppliers. Maabar operates solely as a neutral commercial intermediary and is not a party to any transaction concluded between users. Responsibility for verifying products, quality, and delivery terms rests entirely with the contracting parties. Maabar undertakes to manage the payment mechanism and disputes in accordance with what is stipulated in these terms.' },
    { title: '2. Registration Terms', body: 'For traders:\n▪ Must be resident in, or operating a business in, Saudi Arabia.\n▪ Must confirm the accuracy of the data provided during registration.\nFor suppliers:\n▪ Must have a valid commercial registration.\n▪ Subject to Maabar review and approval before account activation; approval may take 3-5 business days.\nMaabar reserves the right to suspend or cancel any account that violates these terms.' },
    { title: '3. Contract Formation', body: 'Transactions are formed through an offer-and-acceptance mechanism:\n▪ The trader posts a detailed request for the required product.\n▪ Suppliers submit offers according to the request specifications.\n▪ The trader selects the most suitable offer and confirms it.\nThe contract becomes binding on both parties once the trader transfers the first installment. Prior to transfer, both parties may cancel the request or withdraw the offer without any financial obligation. Maabar retains a digital record of each concluded contract for 3 years.' },
    { title: '4. Staged Payment System', body: 'Maabar offers three payment options, chosen by the trader upon confirming the transaction:\n\n4.1 30%/70% System\n▪ The trader pays 30% of the transaction value to enable the supplier to begin preparation.\n▪ The first installment (30%) is held and transferred to the supplier upon confirmation of preparation start.\n▪ The trader pays the remaining 70% after receiving a "Shipment Ready" notification from the supplier.\n▪ Maabar holds the second installment (70%) until confirmation of the trader\'s receipt of the goods.\n\n4.2 50%/50% System\n▪ The trader pays 50% upfront with priority in the preparation schedule.\n▪ The trader pays the remaining 50% after the "Shipment Ready" notification.\n▪ Maabar holds the second installment (50%) until confirmation of receipt.\n\n4.3 100% System\n▪ A single full payment accelerates the shipping process.\n▪ The supplier ships immediately upon receiving confirmation from Maabar.\n\nImportant note:\nThe first installment in the 30/70 and 50/50 systems represents the trader\'s commitment and enables the supplier to begin production. Maabar does not release the second installment to the supplier until confirmation of the trader\'s receipt of the goods or the expiry of the designated objection period.' },
    { title: '5. Delivery Time Policy', body: 'The expected delivery time for each transaction is determined separately by agreement between the trader and supplier, and is included in the offer details before transaction confirmation.\nThe supplier is obligated to notify the trader immediately upon shipment readiness, and of any expected delay prior to the agreed shipping date. The period stated in the approved offer is an integral part of the binding agreement between the parties.' },
    { title: '6. Platform Fees and Commission', body: 'Maabar currently operates with 4% fees on transactions concluded via the platform.\nMaabar reserves the right to modify the fee structure in the future, with registered users notified 30 days prior to the effective date of any change.' },
    { title: '7. Permitted and Prohibited Goods', body: 'The platform is limited to transactions involving goods licensed under Saudi trade regulations. The following are prohibited from being traded via Maabar:\n▪ Counterfeit products or those infringing intellectual property rights.\n▪ Goods requiring a Saudi Conformity Certificate (SASO) without obtaining it.\n▪ Food and pharmaceutical products without approval from the Saudi Food and Drug Authority.\n▪ Weapons, ammunition, and accessories of all kinds.\n▪ Narcotic drugs and psychotropic substances.\n▪ Any goods prohibited from import or trade under Saudi regulations or applicable international agreements in the Kingdom.\nThe trader and supplier bear full legal responsibility for any violation of this clause.' },
    { title: '8. Trader Rights and Obligations', body: 'Rights:\n▪ Access complete offers from approved suppliers.\n▪ Request refunds in proven cases of default as per Article 10.\n▪ Rate suppliers after transaction completion.\n▪ Communicate with Maabar support team at any time.\nObligations:\n▪ Provide accurate and complete information in purchase requests.\n▪ Commit to payment after accepting an offer according to the chosen system.\n▪ Report any problem within 7 days of actual receipt date.\n▪ Conduct all payments exclusively through the Maabar platform.' },
    { title: '9. Supplier Rights and Obligations', body: 'Rights:\n▪ Receive payments according to the schedule agreed in the transaction.\n▪ Respond to complaints and provide sufficient documentation to defend their position.\nObligations:\n▪ Adhere to the product specifications agreed in the approved offer.\n▪ Deliver within the period specified in the transaction.\n▪ Notify the trader immediately of any expected delay with reasons.\n▪ Not request any payments outside the Maabar platform under any name.' },
    { title: '10. Refund and Issues Policy', body: '10.1 Damaged or non-conforming goods:\n▪ The trader has 7 days from actual receipt to file a documented complaint with photos or video.\n▪ Maabar reviews the complaint within 3 business days and issues its decision.\n▪ If default is proven: Maabar returns the held installment to the trader and temporarily suspends the supplier account.\n\n10.2 Non-shipment after receiving the second installment:\n▪ The trader may file an immediate complaint.\n▪ Maabar intervenes, temporarily suspends the supplier account, and returns the entire held second installment to the trader.\n\n10.3 First installment in the 30%/70% system:\nThe 30% is transferred to the supplier upon confirmation of preparation start, as it represents the cost of raw materials and actual production. If supplier default is proven before actual preparation begins, Maabar recovers this amount and returns it in full to the trader.\n\n10.4 First installment in the 50%/50% system:\nThe 50% remains held by Maabar and is not transferred to the supplier until shipment readiness is confirmed. If supplier default is proven, Maabar returns this amount in full to the trader.\n\n10.5 Maabar\'s decision in disputes is final and binding on both parties.' },
    { title: '11. Dispute Settlement', body: 'Maabar undertakes to decide on disputes within 7 business days of receiving a complete complaint with its evidence. Maabar acts as a neutral party and relies solely on the evidence presented by the parties.\nMaabar\'s decision is final and binding within the platform. If any party wishes to pursue external litigation, the Saudi judiciary has jurisdiction over the dispute in accordance with the Kingdom\'s regulations.' },
    { title: '12. Contact and Support', body: 'You can contact the Maabar team through the following channels:\n▪ Email: support@maabar.io\nFor formal complaints: Send a detailed email to support@maabar.io with the transaction number and attached evidence.' },
    { title: '13. Privacy and Data Protection', body: 'Maabar complies with the Saudi Personal Data Protection Law (PDPL). We collect only the data necessary to operate the platform — such as name, email, and transaction data — and do not sell or share it with any third party except under a judicial order or regulatory requirement.\nEach user has the right at any time to:\n▪ Request access to their personal data held by us.\n▪ Request correction of any inaccurate data.\n▪ Request deletion of their data after the contractual relationship ends, subject to legal retention for 3 years.\nTo contact regarding privacy: support@maabar.io' },
    { title: '14. Technical Security', body: 'Maabar adopts the following technical measures to protect user data:\n▪ Valid SSL certificate to encrypt all data exchanged between the user and the platform.\n▪ Strict database control policies (Row Level Security) ensuring each user accesses only their own data.\n▪ Payment and bank card data does not pass through Maabar servers nor is stored there — processed directly through the Maysir gateway licensed by the Saudi Central Bank (SAMA).\nIn the event of a security breach affecting user data, Maabar undertakes to notify affected users within 72 hours of discovering the breach in accordance with the requirements of the National Cybersecurity Authority.' },
    { title: '15. Prohibited Goods — User Acknowledgement', body: 'By accepting these terms, each trader and supplier acknowledges that they will not use Maabar to trade any prohibited goods under Article 7. Maabar reserves the right to cancel any transaction and freeze the account immediately upon detecting any violation, without refunding any payments associated with the violating transaction.' },
    { title: '16. Amendment of Terms', body: 'Maabar reserves the right to amend these terms at any time. Registered users must be notified of any material amendment at least 30 days before its effective date via the registered email.\nContinued use of the platform after the amendment constitutes implied acceptance of all amendments.' },
    { title: '17. Record Keeping', body: 'Maabar retains records of contracts, communications, and payments for 3 years from the date the transaction is completed or terminated.' },
    { title: '18. Governing Jurisdiction', body: 'These terms are subject to the regulations of the Kingdom of Saudi Arabia. If a dispute is not resolved through Maabar\'s internal mechanism, the Saudi judiciary has jurisdiction over it.' },
  ],
  zh: [
    { title: '1. 平台定义', body: 'Maabar 是一个电子贸易中介平台，连接沙特贸易商与中国供应商。Maabar 仅作为中立的商业中介运营，并非用户之间所达成任何交易的合同方。产品核验、质量判断以及交付条款的确认责任完全由缔约双方承担。Maabar 承诺按照本条款规定管理支付机制和争议。' },
    { title: '2. 注册条款', body: '贸易商：\n▪ 须在沙特阿拉伯居住或经营业务。\n▪ 须确认注册时提供的数据准确无误。\n供应商：\n▪ 须持有有效的商业登记。\n▪ 账户激活前须经 Maabar 审核批准；审核可能需要 3-5 个工作日。\n如账户违反本条款，Maabar 保留暂停或取消账户的权利。' },
    { title: '3. 合同成立方式', body: '交易通过"报价—接受"机制成立：\n▪ 贸易商发布所需产品的详细需求。\n▪ 供应商根据需求规格提交报价。\n▪ 贸易商选择最合适的报价并确认。\n一旦贸易商转出首付款，合同即对双方具有约束力。转款前，双方均可取消需求或撤回报价，不承担任何财务义务。Maabar 会保留每份已成立合同的数字记录 3 年。' },
    { title: '4. 分阶段付款制度', body: 'Maabar 提供三种付款方式，由贸易商在确认交易时选择：\n\n4.1 30%/70% 制度\n▪ 贸易商支付交易价值的 30% 以使供应商能够开始准备。\n▪ 首付款（30%）在确认开始准备后转给供应商。\n▪ 贸易商在收到供应商的"货物就绪"通知后支付剩余的 70%。\n▪ Maabar 持有第二笔款项（70%）直至确认贸易商收到货物。\n\n4.2 50%/50% 制度\n▪ 贸易商预付 50%，享有准备进度的优先权。\n▪ 贸易商在"货物就绪"通知后支付剩余的 50%。\n▪ Maabar 持有第二笔款项（50%）直至确认收货。\n\n4.3 100% 制度\n▪ 一次性全额付款可加快发货流程。\n▪ 供应商在收到 Maabar 确认后立即发货。\n\n重要提示：\n30/70 和 50/50 制度中的首付款代表贸易商的交易承诺，并使供应商能够开始生产。Maabar 不会向供应商释放第二笔款项，直至确认贸易商收到货物或指定的异议期届满。' },
    { title: '5. 交货时间政策', body: '每笔交易的预计交货时间由贸易商与供应商另行约定，并在交易确认前包含在报价详情中。\n供应商有义务在货物就绪时立即通知贸易商，并在约定的发货日期前通知任何预期的延迟。经批准的报价中所述期限是双方之间具有约束力协议不可分割的一部分。' },
    { title: '6. 平台费用与佣金', body: 'Maabar 目前对通过平台达成的交易收取 4% 费用。\nMaabar 保留未来修改费用结构的权利，任何变更生效前 30 天通知注册用户。' },
    { title: '7. 允许与禁止的商品', body: '本平台仅限于涉及符合沙特贸易法规的许可商品的交易。禁止通过 Maabar 交易以下任何商品：\n▪ 假冒产品或侵犯知识产权的产品。\n▪ 需要沙特符合性证书（SASO）但未获得的商品。\n▪ 未经沙特食品和药物管理局批准的食品和药品。\n▪ 各种类型的武器、弹药及配件。\n▪ 麻醉药品和精神药物。\n▪ 根据沙特法规或王国适用的国际协议禁止进口或贸易的任何商品。\n贸易商和供应商对违反本条承担全部法律责任。' },
    { title: '8. 贸易商的权利与义务', body: '权利：\n▪ 查看已批准供应商的完整报价。\n▪ 根据第 10 条在供应商违约得到证实时要求退款。\n▪ 在交易完成后评价供应商。\n▪ 随时与 Maabar 支持团队沟通。\n义务：\n▪ 在购买需求中提供准确完整的信息。\n▪ 在接受报价后按照所选制度履行付款义务。\n▪ 在实际收货日期起 7 天内报告任何问题。\n▪ 所有付款均须通过 Maabar 平台进行。' },
    { title: '9. 供应商的权利与义务', body: '权利：\n▪ 按照交易中约定的时间表收款。\n▪ 回应投诉并提供充分的证明材料以维护其立场。\n义务：\n▪ 遵守经批准的报价中约定的产品规格。\n▪ 在交易规定的时间内交付。\n▪ 立即通知贸易商任何预期的延迟并说明原因。\n▪ 不得以任何名义要求在 Maabar 平台外付款。' },
    { title: '10. 退款与问题政策', body: '10.1 损坏或与描述不符的商品：\n▪ 贸易商在实际收货后 7 天内可提交附有照片或视频记录的投诉。\n▪ Maabar 在 3 个工作日内审核投诉并作出决定。\n▪ 若违约得到证实：Maabar 将持有的款项退还给贸易商并暂时暂停供应商账户。\n\n10.2 收到第二笔款项后未发货：\n▪ 贸易商可立即提交投诉。\n▪ Maabar 介入，暂时暂停供应商账户，并将全部持有的第二笔款项退还给贸易商。\n\n10.3 30%/70% 制度中的首付款：\n30% 在确认开始准备后转给供应商，因为它代表原材料和实际生产的成本。若在供应商实际开始准备前证实其违约，Maabar 追回该金额并全额退还给贸易商。\n\n10.4 50%/50% 制度中的首付款：\n50% 由 Maabar 持有，直至确认货物就绪后才转给供应商。若证实供应商违约，Maabar 将该金额全额退还给贸易商。\n\n10.5 Maabar 在争议中的决定为最终决定，并对双方具有约束力。' },
    { title: '11. 争议解决', body: 'Maabar 承诺在收到完整投诉及其证据后的 7 个工作日内对争议作出决定。Maabar 作为中立方，仅依据双方提供的证据作出决定。\nMaabar 的决定在平台内为最终决定且具有约束力。若任何一方希望提起外部诉讼，沙特司法机关根据王国法规对争议具有管辖权。' },
    { title: '12. 联系与支持', body: '您可以通过以下渠道联系 Maabar 团队：\n▪ 电子邮件：support@maabar.io\n正式投诉：发送详细电子邮件至 support@maabar.io，注明交易编号并附上证据。' },
    { title: '13. 隐私与数据保护', body: 'Maabar 遵守沙特个人数据保护法（PDPL）。我们仅收集运营平台所需的数据——例如姓名、电子邮件和交易数据——除司法命令或监管要求外，不会向任何第三方出售或共享。\n每位用户有权随时：\n▪ 要求访问我们持有的其个人数据。\n▪ 要求更正任何不准确的数据。\n▪ 在合同关系结束后要求删除其数据，但依法保留 3 年。\n有关隐私的联系方式：support@maabar.io' },
    { title: '14. 技术安全', body: 'Maabar 采取以下技术措施保护用户数据：\n▪ 有效的 SSL 证书加密用户与平台之间交换的所有数据。\n▪ 严格的数据库控制策略（行级安全），确保每位用户仅访问自己的数据。\n▪ 支付和银行卡数据不经过 Maabar 服务器也不存储其中——直接通过沙特中央银行（SAMA）许可的 Maysir 网关处理。\n如发生影响用户数据的安全漏洞，Maabar 承诺在发现漏洞后 72 小时内根据国家网络安全局的要求通知受影响用户。' },
    { title: '15. 禁止商品 — 用户确认', body: '接受本条款即表示每位贸易商和供应商确认不会使用 Maabar 交易第 7 条规定的任何禁止商品。Maabar 保留在发现任何违规时立即取消交易并冻结账户的权利，且不退还与违规交易相关的任何款项。' },
    { title: '16. 条款修改', body: 'Maabar 保留随时修改本条款的权利。重大修改须至少提前 30 天通过注册电子邮件通知注册用户。\n修改生效后继续使用平台即视为默示接受所有修改。' },
    { title: '17. 记录保存', body: 'Maabar 自交易完成或终止之日起保存合同、沟通记录及付款记录 3 年。' },
    { title: '18. 管辖法院', body: '本条款受沙特阿拉伯王国法规管辖。若争议无法通过 Maabar 内部机制解决，则由沙特司法机关管辖。' },
  ],
};
