import React, { useEffect, useState } from 'react';
import { fetchOrderInvoice, saveOrderInvoice, issueOrderInvoice, defaultLineItem } from '../lib/orderInvoice';

// Direct-order invoice — shown to the supplier (create/edit/issue) and the buyer
// (view/print once issued). Generated by Maabar on behalf of the supplier: the
// supplier fills the line items + trade details; the 5% Maabar fee is a visible
// line; the document is numbered by request_ref and immutable once issued.

const T = {
  ar: {
    title: 'فاتورة', draft: 'مسودة', issued: 'صادرة', from: 'صادرة من', to: 'إلى (المشتري)',
    onBehalf: 'صادرة عبر مَعبر نيابةً عن المورّد', desc: 'الوصف', qty: 'الكمية', unit: 'سعر الوحدة',
    amount: 'الإجمالي', subtotal: 'إجمالي البضاعة', fee: 'رسوم منصة مَعبر (5%)', total: 'الإجمالي',
    incoterms: 'شروط التسليم (Incoterms)', port: 'ميناء الشحن', hs: 'HS code', notes: 'ملاحظات',
    addRow: '+ سطر', save: 'حفظ المسودة', issue: 'إصدار للتاجر', print: 'طباعة / حفظ PDF',
    close: 'إغلاق', notIssued: 'لم تُصدر الفاتورة بعد.', saving: 'جارٍ الحفظ…', number: 'رقم الفاتورة',
    onBehalfNote: 'صادرة عبر مَعبر نيابةً عن المورّد كوثيقة رسمية للبضاعة والدفع. الشحن والتخليص الجمركي بين الطرفين.',
    issuedOk: 'صدرت الفاتورة ووصلت التاجر.', immutable: 'نسخة رسمية غير قابلة للتعديل.',
  },
  en: {
    title: 'Invoice', draft: 'Draft', issued: 'Issued', from: 'From', to: 'To (Buyer)',
    onBehalf: 'Issued via Maabar on behalf of the supplier', desc: 'Description', qty: 'Qty', unit: 'Unit price',
    amount: 'Amount', subtotal: 'Goods subtotal', fee: 'Maabar platform fee (5%)', total: 'Total',
    incoterms: 'Incoterms', port: 'Port of loading', hs: 'HS code', notes: 'Notes',
    addRow: '+ Row', save: 'Save draft', issue: 'Issue to buyer', print: 'Print / Save PDF',
    close: 'Close', notIssued: 'The invoice has not been issued yet.', saving: 'Saving…', number: 'Invoice no.',
    onBehalfNote: 'Issued via Maabar on behalf of the supplier as an official goods & payment document. Shipping & customs are between the two parties.',
    issuedOk: 'Invoice issued and delivered to the buyer.', immutable: 'Official copy — not editable.',
  },
};

const money = (n, cur) => `${(Number(n) || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${cur || 'SAR'}`;

export default function OrderInvoiceModal({ requestId, order, role, lang = 'ar', onClose }) {
  const t = T[lang] || T.ar;
  const isAr = lang === 'ar';
  const isSupplier = role === 'supplier';
  const [inv, setInv] = useState(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [items, setItems] = useState([]);
  const [incoterms, setIncoterms] = useState('');
  const [port, setPort] = useState('');
  const [hs, setHs] = useState('');
  const [notes, setNotes] = useState('');
  const currency = order?.currency || inv?.currency || 'SAR';

  useEffect(() => {
    (async () => {
      const data = await fetchOrderInvoice(requestId);
      if (data) {
        setInv(data);
        setItems(Array.isArray(data.line_items) && data.line_items.length ? data.line_items : defaultLineItem(order));
        setIncoterms(data.incoterms || ''); setPort(data.port_of_loading || '');
        setHs(data.hs_code || ''); setNotes(data.notes || '');
      } else {
        setItems(defaultLineItem(order));
      }
      setLoading(false);
    })();
  }, [requestId]); // eslint-disable-line react-hooks/exhaustive-deps

  const editable = isSupplier && (!inv || inv.status === 'draft');
  const subtotal = items.reduce((s, it) => s + (Number(it.qty) || 0) * (Number(it.unit_price) || 0), 0);
  const fee = Math.round(subtotal * 5) / 100;
  const total = subtotal + fee;
  const invoiceNo = inv?.invoice_number || order?.request_ref || '—';
  const buyerName = order?.buyer_name || inv?.buyer_name || '—';
  const supplierName = order?.supplier_name || '—';

  const setItem = (i, k, v) => setItems(prev => prev.map((it, idx) => idx === i ? { ...it, [k]: v } : it));
  const addRow = () => setItems(prev => [...prev, { desc: '', qty: 1, unit_price: 0 }]);
  const rmRow = (i) => setItems(prev => prev.filter((_, idx) => idx !== i));

  const buildPayload = () => ({
    lineItems: items.map(it => ({
      desc: it.desc || '', qty: Number(it.qty) || 0, unit_price: Number(it.unit_price) || 0,
      amount: (Number(it.qty) || 0) * (Number(it.unit_price) || 0),
    })),
    incoterms, port, hsCode: hs, notes, currency,
  });

  const doSave = async () => {
    setBusy(true);
    try { const r = await saveOrderInvoice(requestId, buildPayload()); setInv(r); }
    catch (e) { alert(e.message || 'Error'); }
    setBusy(false);
  };
  const doIssue = async () => {
    setBusy(true);
    try { await saveOrderInvoice(requestId, buildPayload()); const r = await issueOrderInvoice(requestId); setInv(r); alert(t.issuedOk); }
    catch (e) { alert(e.message || 'Error'); }
    setBusy(false);
  };

  const doPrint = () => {
    const rows = items.map(it => `<tr><td>${(it.desc || '').replace(/</g, '&lt;')}</td><td style="text-align:${isAr ? 'left' : 'right'}">${Number(it.qty) || 0}</td><td style="text-align:${isAr ? 'left' : 'right'}">${money(it.unit_price, currency)}</td><td style="text-align:${isAr ? 'left' : 'right'}">${money((Number(it.qty) || 0) * (Number(it.unit_price) || 0), currency)}</td></tr>`).join('');
    const html = `<!doctype html><html dir="${isAr ? 'rtl' : 'ltr'}" lang="${lang}"><head><meta charset="utf-8"><title>${t.title} ${invoiceNo}</title>
      <style>body{font-family:'Segoe UI',Tahoma,Arial,sans-serif;color:#16202A;max-width:820px;margin:24px auto;padding:0 20px}
      .band{background:#0C6B5A;color:#fff;padding:22px 26px;border-radius:12px;display:flex;justify-content:space-between}
      .mark{font-size:26px;font-weight:700}.small{font-size:11px;letter-spacing:3px;opacity:.85}
      h2{font-weight:400}table{width:100%;border-collapse:collapse;margin:16px 0}
      th{color:#8A97A5;font-size:11px;text-align:${isAr ? 'right' : 'left'};border-bottom:2px solid #cfd6dd;padding:10px 8px}
      td{padding:11px 8px;border-bottom:1px solid #E4E8ED;font-size:13px}
      .tot{margin-inline-start:auto;width:300px}.tot .r{display:flex;justify-content:space-between;padding:7px 0;font-size:13px}
      .tot .g{background:#0C6B5A;color:#fff;padding:12px 14px;border-radius:10px;font-weight:700;margin-top:6px}
      .fee{color:#0a5849;font-weight:600}.parties{display:flex;gap:24px;margin:16px 0}.parties>div{flex:1}
      .lbl{font-size:11px;color:#0C6B5A;font-weight:700}.behalf{display:inline-block;margin-top:6px;font-size:11px;background:#E9F2EF;color:#0a5849;padding:3px 8px;border-radius:6px}
      .note{font-size:11px;color:#5C6B7A;line-height:1.8;margin-top:12px}</style></head>
      <body onload="window.print()">
      <div class="band"><div><div class="mark">مَعبر</div><div class="small">MAABAR</div></div>
      <div style="text-align:${isAr ? 'left' : 'right'}"><div style="font-size:18px">${t.title}</div><div class="small">${invoiceNo} · ${new Date().toISOString().slice(0, 10)}</div></div></div>
      <div class="parties"><div><div class="lbl">${t.to}</div><div style="font-weight:700">${buyerName}</div></div>
      <div><div class="lbl">${t.from}</div><div style="font-weight:700">${supplierName}</div><span class="behalf">${t.onBehalf}</span></div></div>
      <table><thead><tr><th>${t.desc}</th><th style="text-align:${isAr ? 'left' : 'right'}">${t.qty}</th><th style="text-align:${isAr ? 'left' : 'right'}">${t.unit}</th><th style="text-align:${isAr ? 'left' : 'right'}">${t.amount}</th></tr></thead><tbody>${rows}</tbody></table>
      <div class="tot"><div class="r"><span>${t.subtotal}</span><span>${money(subtotal, currency)}</span></div>
      <div class="r fee"><span>${t.fee}</span><span>${money(fee, currency)}</span></div>
      <div class="g" style="display:flex;justify-content:space-between"><span>${t.total}</span><span>${money(total, currency)}</span></div></div>
      <div class="note">${t.onBehalfNote}<br>${t.immutable}</div></body></html>`;
    const w = window.open('', '_blank');
    if (w) { w.document.write(html); w.document.close(); }
  };

  const inputStyle = { width: '100%', padding: '7px 9px', border: '1px solid var(--border)', borderRadius: 8, background: 'var(--bg-base)', color: 'var(--text-primary)', fontSize: 13 };

  return (
    <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 1000, display: 'flex', alignItems: 'flex-start', justifyContent: 'center', overflowY: 'auto', padding: '24px 12px' }}>
      <div onClick={e => e.stopPropagation()} dir={isAr ? 'rtl' : 'ltr'} style={{ background: 'var(--bg-overlay)', borderRadius: 16, maxWidth: 720, width: '100%', padding: 0, overflow: 'hidden', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ background: 'linear-gradient(135deg,#0C6B5A,#0a5849)', color: '#fff', padding: '20px 26px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ fontSize: 22, fontWeight: 700 }}>مَعبر</div>
            <div style={{ fontSize: 10, letterSpacing: 3, opacity: 0.85 }}>MAABAR</div>
          </div>
          <div style={{ textAlign: isAr ? 'left' : 'right' }}>
            <div style={{ fontSize: 16 }}>{t.title}</div>
            <span style={{ fontSize: 11, background: 'rgba(255,255,255,0.16)', padding: '3px 10px', borderRadius: 999 }}>
              {inv?.status === 'issued' ? t.issued : t.draft} · {invoiceNo}
            </span>
          </div>
        </div>

        <div style={{ padding: '20px 26px', maxHeight: '68vh', overflowY: 'auto' }}>
          {loading ? <p style={{ color: 'var(--text-secondary)' }}>…</p> : (
            (!isSupplier && (!inv || inv.status !== 'issued')) ? (
              <p style={{ color: 'var(--text-secondary)', padding: '30px 0', textAlign: 'center' }}>{t.notIssued}</p>
            ) : (
            <>
              {/* Parties */}
              <div style={{ display: 'flex', gap: 20, marginBottom: 16, flexWrap: 'wrap' }}>
                <div style={{ flex: 1, minWidth: 200 }}>
                  <div style={{ fontSize: 11, color: 'var(--accent, #0C6B5A)', fontWeight: 700 }}>{t.to}</div>
                  <div style={{ fontWeight: 700, color: 'var(--text-primary)' }}>{buyerName}</div>
                </div>
                <div style={{ flex: 1, minWidth: 200 }}>
                  <div style={{ fontSize: 11, color: 'var(--accent, #0C6B5A)', fontWeight: 700 }}>{t.from}</div>
                  <div style={{ fontWeight: 700, color: 'var(--text-primary)' }}>{supplierName}</div>
                  <span style={{ display: 'inline-block', marginTop: 6, fontSize: 11, background: '#E9F2EF', color: '#0a5849', padding: '3px 8px', borderRadius: 6, fontWeight: 600 }}>{t.onBehalf}</span>
                </div>
              </div>

              {/* Line items */}
              <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 14 }}>
                <thead>
                  <tr style={{ borderBottom: '2px solid var(--border)' }}>
                    <th style={{ textAlign: 'start', fontSize: 11, color: 'var(--text-secondary)', padding: '8px 6px' }}>{t.desc}</th>
                    <th style={{ textAlign: 'end', fontSize: 11, color: 'var(--text-secondary)', padding: '8px 6px', width: 70 }}>{t.qty}</th>
                    <th style={{ textAlign: 'end', fontSize: 11, color: 'var(--text-secondary)', padding: '8px 6px', width: 110 }}>{t.unit}</th>
                    <th style={{ textAlign: 'end', fontSize: 11, color: 'var(--text-secondary)', padding: '8px 6px', width: 110 }}>{t.amount}</th>
                    {editable && <th style={{ width: 28 }} />}
                  </tr>
                </thead>
                <tbody>
                  {items.map((it, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid var(--border-muted)' }}>
                      <td style={{ padding: '7px 6px' }}>
                        {editable ? <input style={inputStyle} value={it.desc || ''} onChange={e => setItem(i, 'desc', e.target.value)} /> : <span style={{ fontSize: 13, color: 'var(--text-primary)' }}>{it.desc}</span>}
                      </td>
                      <td style={{ padding: '7px 6px', textAlign: 'end' }}>
                        {editable ? <input style={{ ...inputStyle, textAlign: 'end' }} type="number" value={it.qty} onChange={e => setItem(i, 'qty', e.target.value)} /> : <span style={{ fontSize: 13 }}>{it.qty}</span>}
                      </td>
                      <td style={{ padding: '7px 6px', textAlign: 'end' }}>
                        {editable ? <input style={{ ...inputStyle, textAlign: 'end' }} type="number" value={it.unit_price} onChange={e => setItem(i, 'unit_price', e.target.value)} /> : <span style={{ fontSize: 13 }}>{money(it.unit_price, currency)}</span>}
                      </td>
                      <td style={{ padding: '7px 6px', textAlign: 'end', fontSize: 13, fontWeight: 600 }}>{money((Number(it.qty) || 0) * (Number(it.unit_price) || 0), currency)}</td>
                      {editable && <td style={{ textAlign: 'center' }}>{items.length > 1 && <button onClick={() => rmRow(i)} style={{ background: 'none', border: 'none', color: 'var(--text-tertiary)', cursor: 'pointer', fontSize: 16 }}>×</button>}</td>}
                    </tr>
                  ))}
                </tbody>
              </table>
              {editable && <button onClick={addRow} style={{ background: 'none', border: '1px dashed var(--border)', borderRadius: 8, padding: '6px 12px', color: 'var(--text-secondary)', cursor: 'pointer', fontSize: 12, marginBottom: 14 }}>{t.addRow}</button>}

              {/* Trade fields */}
              {editable && (
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 14 }}>
                  <div><label style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{t.incoterms}</label><input style={inputStyle} value={incoterms} onChange={e => setIncoterms(e.target.value)} placeholder="FOB …" /></div>
                  <div><label style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{t.port}</label><input style={inputStyle} value={port} onChange={e => setPort(e.target.value)} /></div>
                  <div><label style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{t.hs}</label><input style={inputStyle} value={hs} onChange={e => setHs(e.target.value)} /></div>
                  <div><label style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{t.notes}</label><input style={inputStyle} value={notes} onChange={e => setNotes(e.target.value)} /></div>
                </div>
              )}

              {/* Totals */}
              <div style={{ marginInlineStart: 'auto', maxWidth: 300 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', fontSize: 13, color: 'var(--text-secondary)' }}><span>{t.subtotal}</span><span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{money(subtotal, currency)}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', fontSize: 13, color: '#0a5849', fontWeight: 600 }}><span>{t.fee}</span><span>{money(fee, currency)}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 14px', marginTop: 6, background: '#0C6B5A', color: '#fff', borderRadius: 10, fontWeight: 700 }}><span>{t.total}</span><span>{money(total, currency)}</span></div>
              </div>
            </>
            )
          )}
        </div>

        {/* Actions */}
        <div style={{ padding: '14px 26px', borderTop: '1px solid var(--border-muted)', display: 'flex', gap: 10, justifyContent: 'flex-end', flexWrap: 'wrap' }}>
          <button onClick={onClose} style={{ padding: '9px 16px', borderRadius: 8, border: '1px solid var(--border)', background: 'none', color: 'var(--text-secondary)', cursor: 'pointer', fontSize: 13 }}>{t.close}</button>
          {(inv?.status === 'issued' || !isSupplier) && inv?.status === 'issued' && (
            <button onClick={doPrint} style={{ padding: '9px 16px', borderRadius: 8, border: 'none', background: 'var(--text-primary)', color: 'var(--bg-base)', cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>{t.print}</button>
          )}
          {editable && (
            <>
              <button onClick={doSave} disabled={busy} style={{ padding: '9px 16px', borderRadius: 8, border: '1px solid #0C6B5A', background: 'none', color: '#0C6B5A', cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>{busy ? t.saving : t.save}</button>
              <button onClick={doIssue} disabled={busy} style={{ padding: '9px 16px', borderRadius: 8, border: 'none', background: '#0C6B5A', color: '#fff', cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>{t.issue}</button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
