-- Latin-script (pinyin/romanized) rendering of a supplier's company name.
--
-- Chinese company names must never be machine-TRANSLATED into Arabic (that
-- produces nonsense for proper nouns). Instead we ROMANIZE them — pinyin for
-- the proper-noun part, conventional English for legal suffixes (Co., Ltd) and
-- generic industry terms — e.g. 江阴标榜塑料制品有限公司 → "Jiangyin Biaobang
-- Plastic Products Co., Ltd". This is a DIFFERENT operation from translation and
-- deliberately does NOT reuse bio_ar/bio_en/bio_zh or the chat_translation path.
--
-- Populated by the maabar-ai edge task `company_romanization` (LLM), written
-- back under the service role and only when currently empty. Buyer surfaces read
-- `company_name_latin || company_name`, so a null here simply falls back to the
-- raw name — never blank.
begin;

alter table public.profiles
  add column if not exists company_name_latin text;

comment on column public.profiles.company_name_latin is
  'Latin-script romanization (pinyin + conventional English) of a Chinese company_name. Generated by the maabar-ai company_romanization task. Display fallback: company_name_latin || company_name. Never a translation.';

-- Expose on the buyer-facing view. create-or-replace can only APPEND columns
-- (Postgres keeps existing column order/type), so company_name_latin goes last.
-- Everything above the new line is byte-for-byte the current definition
-- (20260726000002) so no existing consumer .select() breaks.
create or replace view public.supplier_public_profiles as
select
  p.id,
  p.full_name,
  p.role,
  p.company_name,
  p.avatar_url,
  p.status,
  p.rating,
  p.reviews_count,
  p.city,
  p.country,
  p.trade_link,
  p.wechat,
  p.whatsapp,
  p.factory_images,
  p.years_experience,
  p.maabar_supplier_id,
  p.min_order_value,
  p.speciality,
  p.company_website,
  p.company_description,
  p.bio_ar,
  p.bio_en,
  p.bio_zh,
  p.business_type,
  p.year_established,
  p.customization_support,
  p.company_address,
  p.languages,
  p.export_markets,
  p.export_years,
  p.certifications,
  null::int as deals_completed,
  p.completion_rate,
  (
    select count(*)::int
    from public.products pr
    where pr.supplier_id = p.id
      and coalesce(pr.is_active, false) = true
  ) as product_count,
  p.company_name_latin
from public.profiles p
where lower(coalesce(p.role, '')) = 'supplier'
  and lower(coalesce(p.status, '')) not in ('rejected', 'inactive');

alter view public.supplier_public_profiles set (security_invoker = false);
revoke all on table public.supplier_public_profiles from public;
grant select on table public.supplier_public_profiles to anon, authenticated;

-- Same for the general identity directory (chat/offers/requests name attach).
create or replace view public.profile_directory as
select
  p.id,
  p.role,
  p.status,
  p.full_name,
  p.company_name,
  p.avatar_url,
  p.city,
  p.country,
  p.speciality,
  p.maabar_supplier_id,
  p.trade_link,
  p.lang,
  p.rating,
  p.reviews_count,
  p.years_experience,
  p.year_established,
  p.factory_images,
  p.company_name_latin
from public.profiles p;

alter view public.profile_directory set (security_invoker = false);
revoke all on table public.profile_directory from public;
grant select on table public.profile_directory to authenticated;

commit;
