-- Phase 3 (invoicing) step 3a — supplier-issued invoice for a direct order,
-- generated BY Maabar on behalf of the supplier and delivered to the trader.
--
-- Model (see the agreed design): the supplier fills goods line items + trade
-- details; Maabar computes the goods subtotal, the VISIBLE 5% platform fee, and
-- the total, and issues the document. Numbered by requests.request_ref. Immutable
-- once issued. The supplier of a DIRECT order is products.supplier_id (a real
-- supplier profile), resolved via requests.product_ref (text holding the uuid).
--
-- Amounts here are the invoice's own snapshot (computed from the line items), so
-- this is independent of / forward-compatible with the Telr payment work (Phase 4)
-- which will charge goods + 5% through the gateway.
begin;

create table if not exists public.order_invoices (
  id                uuid primary key default gen_random_uuid(),
  request_id        uuid not null unique references public.requests(id) on delete cascade,
  supplier_id       uuid not null references public.profiles(id),
  buyer_id          uuid not null references public.profiles(id),
  invoice_number    text not null,                    -- = requests.request_ref (M-#####)
  line_items        jsonb not null default '[]'::jsonb, -- [{desc, qty, unit_price, amount}]
  incoterms         text,
  port_of_loading   text,
  hs_code           text,
  notes             text,
  currency          text not null default 'SAR',
  goods_subtotal    numeric not null default 0,
  maabar_fee_pct    numeric not null default 5,
  maabar_fee_amount numeric not null default 0,
  total             numeric not null default 0,
  status            text not null default 'draft' check (status in ('draft', 'issued')),
  issued_at         timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists order_invoices_supplier_idx on public.order_invoices (supplier_id);
create index if not exists order_invoices_buyer_idx    on public.order_invoices (buyer_id);

alter table public.order_invoices enable row level security;

-- Read: the buyer sees the invoice once ISSUED; the supplier sees their own
-- (draft + issued); admins see all. Writes go only through the RPCs below.
drop policy if exists order_invoices_select on public.order_invoices;
create policy order_invoices_select on public.order_invoices
for select to authenticated
using (
  public.is_admin_user()
  or (supplier_id = auth.uid())
  or (buyer_id = auth.uid() and status = 'issued')
);

-- Is the caller the supplier who owns the product on this direct order?
create or replace function public.is_direct_order_supplier(p_request_id uuid, p_uid uuid default auth.uid())
returns boolean
language sql stable security definer set search_path to 'public'
as $$
  select exists (
    select 1
    from public.requests r
    join public.products p on p.id::text = r.product_ref
    where r.id = p_request_id
      and p.supplier_id = coalesce(p_uid, auth.uid())
  );
$$;

-- Supplier saves / updates the draft invoice. Maabar computes the money.
create or replace function public.save_order_invoice(
  p_request_id uuid,
  p_line_items jsonb,
  p_incoterms  text default null,
  p_port       text default null,
  p_hs_code    text default null,
  p_notes      text default null,
  p_currency   text default 'SAR'
) returns public.order_invoices
language plpgsql security definer set search_path to 'public'
as $$
declare
  v_req      public.requests;
  v_supplier uuid := auth.uid();
  v_subtotal numeric := 0;
  v_fee_pct  numeric := 5;
  v_fee      numeric;
  v_total    numeric;
  v_row      public.order_invoices;
  v_item     jsonb;
begin
  if v_supplier is null then raise exception 'Authentication required.'; end if;
  if not public.is_direct_order_supplier(p_request_id, v_supplier) then
    raise exception 'Only the order''s supplier can issue its invoice.';
  end if;

  select * into v_req from public.requests where id = p_request_id;
  if v_req.id is null then raise exception 'Order not found.'; end if;

  -- Block edits once issued (immutable snapshot).
  select * into v_row from public.order_invoices where request_id = p_request_id;
  if v_row.id is not null and v_row.status = 'issued' then
    raise exception 'This invoice has already been issued and cannot be edited.';
  end if;

  -- Sum the line items (qty * unit_price).
  for v_item in select * from jsonb_array_elements(coalesce(p_line_items, '[]'::jsonb)) loop
    v_subtotal := v_subtotal
      + (coalesce((v_item->>'qty')::numeric, 0) * coalesce((v_item->>'unit_price')::numeric, 0));
  end loop;

  v_fee   := round(v_subtotal * v_fee_pct / 100.0, 2);
  v_total := v_subtotal + v_fee;

  insert into public.order_invoices as oi
    (request_id, supplier_id, buyer_id, invoice_number, line_items, incoterms,
     port_of_loading, hs_code, notes, currency, goods_subtotal, maabar_fee_pct,
     maabar_fee_amount, total, status, updated_at)
  values
    (p_request_id, v_supplier, v_req.buyer_id, coalesce(v_req.request_ref, 'M-' || left(p_request_id::text, 8)),
     coalesce(p_line_items, '[]'::jsonb), p_incoterms, p_port, p_hs_code, p_notes,
     coalesce(p_currency, 'SAR'), v_subtotal, v_fee_pct, v_fee, v_total, 'draft', now())
  on conflict (request_id) do update set
    line_items = excluded.line_items,
    incoterms = excluded.incoterms,
    port_of_loading = excluded.port_of_loading,
    hs_code = excluded.hs_code,
    notes = excluded.notes,
    currency = excluded.currency,
    goods_subtotal = excluded.goods_subtotal,
    maabar_fee_amount = excluded.maabar_fee_amount,
    total = excluded.total,
    updated_at = now()
  returning * into v_row;

  return v_row;
end;
$$;

-- Supplier issues the invoice (locks it + reveals it to the buyer).
create or replace function public.issue_order_invoice(p_request_id uuid)
returns public.order_invoices
language plpgsql security definer set search_path to 'public'
as $$
declare v_row public.order_invoices;
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  if not public.is_direct_order_supplier(p_request_id, auth.uid()) then
    raise exception 'Only the order''s supplier can issue its invoice.';
  end if;
  update public.order_invoices
    set status = 'issued', issued_at = coalesce(issued_at, now()), updated_at = now()
    where request_id = p_request_id
    returning * into v_row;
  if v_row.id is null then raise exception 'Save the invoice before issuing it.'; end if;
  return v_row;
end;
$$;

grant execute on function public.save_order_invoice(uuid, jsonb, text, text, text, text, text) to authenticated;
grant execute on function public.issue_order_invoice(uuid) to authenticated;
grant execute on function public.is_direct_order_supplier(uuid, uuid) to authenticated;

commit;
